### ISSUE TITLE
Maketest Problem

### ISSUE THREAD

**Issue by Fairenough** [ArtRand/signalAlign#12]
I think I have installed all the required module:
user@x499-desktop:/media/user/1- 10TB/Yijun_Tian/signalAlign$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
adium-theme-ubuntu (0.3.4)
h5py (2.7.1)
numpy (1.13.3)
pandas (0.21.0)
pip (9.0.1)
pycurl (7.43.0)
pyliblzma (0.5.3)
pysam (0.13)
pysqlite (1.0.1)
python-dateutil (2.6.1)
pytz (2017.3)
rpm-python (4.12.0.1)
scour (0.32)
setuptools (20.7.0)
six (1.10.0)
unity-lens-photos (1.0)
urlgrabber (3.9.1)
wheel (0.29.0)
yum-metadata-parser (1.1.4)

But after I make test, always went wrong like this:
user@x499-desktop:/media/user/1- 10TB/Yijun_Tian/signalAlign$ make test
#cd .//bin && ./signalAlignLibTests
cd .//bin && ./testSignalAlign
Traceback (most recent call last):
  File "./testSignalAlign", line 11, in <module>
    from alignmentAnalysisLib import get_first_sequence
  File "/media/user/1- 10TB/Yijun_Tian/signalAlign/bin/alignmentAnalysisLib.py", line 8, in <module>
    from serviceCourse.parsers import read_fasta
ImportError: No module named serviceCourse.parsers
Makefile:39: recipe for target 'test' failed
make: *** [test] Error 1

Do you know why?

**Comment by JessicaIrvine** [comment]
Hi 
By chance did you figure out the solution to this problem? 
thanks

**Comment by Fairenough** [comment]
@JessicaIrvine  No. I move to another software after that.. It's called tombo resquiggle. They should have finished all the code and manual in github.

**Comment by JessicaIrvine** [comment]
@Fairenough I managed to get it to work If you are still interested. 
you first make sure it can find the path by typing 
export PYTHONPATH="$PYTHONPATH:$(pwd)"
then you have to move the motif.py file into bin which can be found under scripts 
now the make test should work
