### ISSUE TITLE
install issue import motif

### ISSUE THREAD

**Issue by clarepacini** [ArtRand/signalAlign#13]
Hi,
I'm trying to install signalAlign but get the following error on testing:

#cd .//bin && ./signalAlignLibTests
cd .//bin && ./testSignalAlign
Traceback (most recent call last):
  File "./testSignalAlign", line 12, in <module>
    from signalAlignLib import get_bwa_index, exonerated_bwa, exonerated_bwa_pysam
  File "/home/cep46/signalAlign/bin/signalAlignLib.py", line 13, in <module>
    from motif import getMotif
ImportError: No module named motif
Makefile:39: recipe for target 'test' failed
make: *** [test] Error 1

I have added signalAlign directory to my pythonpath - and have been able to find classes serviceCourse. Where should the motif module be located?

Thanks,

Clare

**Comment by clarepacini** [comment]
Okay, I have moved scripts/motif.py to bin/motif.py and now all tests have completed successfully so hopefully that has solved the problem!
